from django.contrib import admin
from .models import (
    UserProfile, WaterZone, WaterUsage, Alert, Report,
    SystemSettings, ActivityLog, Compliance
)


@admin.register(UserProfile)
class UserProfileAdmin(admin.ModelAdmin):
    list_display = ['get_username', 'role', 'organization', 'timezone', 'created_at']
    list_filter = ['role', 'timezone', 'created_at']
    search_fields = ['user__username', 'user__email', 'organization']

    def get_username(self, obj):
        return obj.user.username
    get_username.short_description = 'Username'


@admin.register(WaterZone)
class WaterZoneAdmin(admin.ModelAdmin):
    list_display = ['name', 'zone_type', 'is_active', 'created_at']
    list_filter = ['zone_type', 'is_active', 'created_at']
    search_fields = ['name', 'description']


@admin.register(WaterUsage)
class WaterUsageAdmin(admin.ModelAdmin):
    list_display = ['zone', 'usage_liters', 'measurement_time', 'quality_percentage', 'is_peak']
    list_filter = ['zone', 'is_peak', 'measurement_time']
    search_fields = ['zone__name']
    readonly_fields = ['created_at']


@admin.register(Alert)
class AlertAdmin(admin.ModelAdmin):
    list_display = ['title', 'alert_type', 'status', 'severity', 'created_at']
    list_filter = ['alert_type', 'status', 'severity', 'created_at']
    search_fields = ['title', 'message']
    readonly_fields = ['created_at']


@admin.register(Report)
class ReportAdmin(admin.ModelAdmin):
    list_display = ['title', 'report_type', 'get_generated_by', 'created_at']
    list_filter = ['report_type', 'created_at']
    search_fields = ['title', 'description']
    readonly_fields = ['created_at']

    def get_generated_by(self, obj):
        return obj.generated_by.username if obj.generated_by else 'Unknown'
    get_generated_by.short_description = 'Generated By'


@admin.register(SystemSettings)
class SystemSettingsAdmin(admin.ModelAdmin):
    list_display = ['organization_name', 'system_version', 'maintenance_mode', 'updated_at']
    readonly_fields = ['updated_at']


@admin.register(ActivityLog)
class ActivityLogAdmin(admin.ModelAdmin):
    list_display = ['get_user', 'action', 'timestamp']
    list_filter = ['action', 'timestamp']
    search_fields = ['user__username', 'action', 'description']
    readonly_fields = ['timestamp']

    def get_user(self, obj):
        return obj.user.username if obj.user else 'Unknown'
    get_user.short_description = 'User'


@admin.register(Compliance)
class ComplianceAdmin(admin.ModelAdmin):
    list_display = ['category', 'status', 'percentage', 'last_checked']
    list_filter = ['status', 'last_checked']
    search_fields = ['category', 'description']
    readonly_fields = ['last_checked']

